namespace EchoSpace.Core.Enums
{
    /// <summary>
    /// Enum representing different sources of images in the system
    /// </summary>
    public enum ImageSource
    {
        /// <summary>
        /// Images uploaded by users (profile photos, post images, etc.)
        /// </summary>
        UserUpload = 1,
        
        /// <summary>
        /// Images generated by AI services
        /// </summary>
        AIGenerated = 2,
        
        /// <summary>
        /// System-generated images (default avatars, placeholders, etc.)
        /// </summary>
        SystemGenerated = 3,
        
        /// <summary>
        /// Images imported from external sources
        /// </summary>
        ExternalImport = 4,
        
        /// <summary>
        /// Other sources
        /// </summary>
        Other = 99
    }
}

